- hosts: localhost

  tasks:
  - name: "apt upgrade"
    become: true
    apt: upgrade=dist force_apt_get=yes

  - name: "Install USER packages from apt"
    become: true
    apt:
      name:
        - git
        - curl
        - zsh
        - exa
      state: present

  - name: "Install DEVELOPMENT packages from apt"
    become: true
    apt:
      name:
        - make
        - libssl-dev
        - build-essential
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - llvm
        - libncursesw5-dev
        - xz-utils
        - tk-dev
        - libxml2-dev
        - libxmlsec1-dev
        - libffi-dev
        - liblzma-dev
      state: present

  - name: "GIT clone dotfiles"
    git:
      repo: https://github.com/jorgepvasconcelos/dotfiles
      dest: ~/dotfiles
      depth: 1
  - name: "Copy ~/dotfiles to ~"
    copy:
      src: ~/dotfiles/
      dest: ~/
  - name: "Delete /dotfiles"
    file:
      path: ~/dotfiles
      state: absent

  - name: "GIT clone PL10K"
    git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: ~/powerlevel10k
      depth: 1
  - name: "GIT clone zsh-autosuggestions"
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions.git
      dest: ~/.zsh/zsh-autosuggestions
      depth: 1
  - name: "GIT clone ASDF"
    git:
      repo: https://github.com/asdf-vm/asdf.git
      dest: ~/.asdf
      version: v0.11.3
      depth: 1

#  - name: "asdasd files"
#    ansible-role-asdf:
#        asdf_plugins:
#        - name: "python"
#          versions: ["latest"]
#          global: "latest"

#  - name: "Set zsh as default shell"
#    shell: "chsh -s /usr/bin/zsh"
##    become: true

